name = "elchef-pages"
compatibility_date = "2024-11-12"
# Use Next-on-Pages prebuilt output directory; for v1.13.x worker is under static
pages_build_output_dir = ".vercel/output/static"

# Enable Node.js built-in module compatibility for Workers runtime
compatibility_flags = ["nodejs_compat"]

## [pages] table is not supported by this runner; using pages_build_output_dir instead

# Build command for Cloudflare Pages (beta config via wrangler.toml)
# Note: Cloudflare Pages UI controls the Build command. This file only sets the output dir.

# Note: Pages config does not support account_id, triggers, or build/observability blocks


