name = "elchef-pages"
compatibility_date = "2024-11-12"
pages_build_output_dir = ".vercel/output/static"

# Enable Node.js built-in module compatibility for Workers runtime
compatibility_flags = ["nodejs_compat"]

## [pages] table is not supported by this runner; using pages_build_output_dir instead

# Environment variables are managed in Cloudflare Pages UI (Production + Preview).
# Remove this comment if you later re-introduce a [vars] block.

# Note: Pages config does not support account_id, triggers, or build/observability blocks


